
export enum ErrorTypeEnum {
    NOT_FOUND = 100,
    PERMISSION_NOT_GRANTED = 200,
    DEVICE_INFO_NOT_MATCHED = -100,
    PHONE_NUMBER_NOT_VALID = -101,
    CODE_NOT_MATCHED = -102,
    PHONE_NUMBER_ALREADY_EXIST = -103,
    NEAR_DISTRICT_NOT_FOUND = -110,
}